version: '3.7'

volumes:
  postgres:
    driver: local

services:
  postgres:
    image: postgres:${POSTGRES_VERSION:-11.4-alpine}
    restart: always
    ports:
      - 0.0.0.0:${POSTGRES_PORT:-5432}:5432
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST_AUTH_METHOD: "trust"
